### ISSUE TITLE
phase2: de-amalgamate deepseek_v4.c and extract shared engine units

### ISSUE THREAD

**Issue by alpibrupa** [alpibrusl/colibri#12]
Two duplication findings from the fork audit (model-implementations reviewer):

**deepseek_v4.c internal**: ~22% of its 11.7k lines are verbatim second/third copies of itself — the ~600-line `attention_token_impl` appears **three times** (1470, 1841, 4865), compressor/indexer twice each, the ~450-line expert store twice (already drifted: `aligned_slab` exists at 5367 but not 9828 — a slab allocated by one copy and freed by the other hits the Windows `_aligned_malloc`/`free` mismatch the file itself warns about), 17 copies of `set_error`. The `_amalgamate_v4.py` script that produced this already implies the per-unit layout.

**Cross-engine**: RMSNorm/softmax/top-k/serve-loop/telemetry re-implemented per engine (~40% structural boilerplate); `route_trace.h:373` documents "fix lands in one engine and not its siblings" as the tree's recurring defect shape (#698, #748, #805, #855, #858, #890, #898 are all instances).

Scope:
- [ ] De-amalgamate deepseek_v4 into per-unit files; shared structs to the internal header; one source of truth per function
- [ ] Extract router selection/renorm, expert-LRU, serve-loop, and telemetry emitters into shared units on the route_trace.h model, parameterized per architecture
- [ ] A tiny HF-referenced Kimi oracle before touching any KDA/MLA code (kimi_k3 is the only engine with no in-repo reference test — the audit's validation gap)

**Comment by alpibrupa** [comment]
Scoping pass before code — the amalgamation script isn't in this repo (upstream-only, or never checked in), but the file's own inline markers (`/* ######## unit.c ######## */`, `/* ---- begin/end include unit.c ---- */`) name every unit it was built from. Full manifest at today's `next` (deepseek_v4.c is 11,779 lines, line numbers have drifted a little from the audit's citations but the shape matches exactly):

```
293   deepseek_v4_layer_resident.c  (includes deepseek_v4_layer.c, 296-570)
634   deepseek_v4_resource_plan.c
807   deepseek_v4_head_cache.c
897   deepseek_v4_expert_store_auto.c  (inlines expert_store_auto_v5.c, 898-1091)   [store copy 1]
1095  deepseek_v4_math.c
1452  deepseek_v4_attention.c                                                       [attn copy 1]
1835  deepseek_v4_attention_batch.c   (includes deepseek_v4_attention.c, 1841-2221) [attn copy 2]
2470  deepseek_v4_compressor.c
2723  deepseek_v4_indexer.c
2972  deepseek_v4_sparse_attention.c
3039  deepseek_v4_block_hybrid.c  (includes block_pipeline.c -> block.c, 3041-3931)
4230  deepseek_v4_compressor_snapshot.c  (includes compressor.c, 4237-4487)
4541  deepseek_v4_indexer_snapshot.c  (includes indexer.c, 4549-4795)
4859  deepseek_v4_attention_transaction.c (includes deepseek_v4_attention.c, 4865-5245) [attn copy 3]
5323  deepseek_v4_expert_store_hot_rows16.c (includes expert_store.c, 5328-5777)     [store copy 2]
6538  deepseek_v4_expert_rows16.c  (includes expert_dual.c, 6540-6621)
6670  deepseek_v4_route_bf16.c
6739  deepseek_v4_runtime.c / engine
7113  deepseek_v4_prompt.c
7178  tools/deepseek_v4_generate_stats.c (includes tools/deepseek_v4_first_token.c, 7193-7636)
9539  deepseek_v4_kv_cache.c
9642  deepseek_v4_attention_cache.c
9719  deepseek_v4_expert.c
9811  deepseek_v4_expert_store.c                                                    [store copy 3]
10260 deepseek_v4_layer.c
10499 deepseek_v4_config.c
```

Two findings sharper than the original audit numbers:

- **`attention_token_impl` is 3 copies of the SAME source unit** (`deepseek_v4_attention.c` literally re-included three times — as itself, inside `_attention_batch.c`, and inside `_attention_transaction.c`), which is good news for de-dup risk: if the three inclusions are byte-identical (need to diff, haven't yet), collapsing to one shared unit called from three call sites is mechanical, not a rewrite.
- **The expert store is 3 copies, not 2** — `expert_store_auto_v5` (897), `expert_store` via `_hot_rows16` (5323→5328), and a bare `expert_store.c` again at 9811. The audit's cited `aligned_slab` drift (present at ~5367, absent at ~9828) falls exactly between copies 2 and 3.

## Kimi oracle feasibility (the issue's precondition on touching KDA/MLA code)

Checked before committing to a plan: `transformers` (5.15.0 here, ahead of the `deepseek-v4-tiny`/`inkling-oracle` jobs' 5.14.1 pin) has `deepseek_v4` and `glm_moe_dsa` natively — confirming why those two oracles are ~100-line scripts — but **no `kimi_k3`** (there's a `kimi_k25`, a vision/video conditional-generation model, unrelated architecture). Kimi K3's hybrid KDA (linear/recurrent attention, likely needs `fla`'s `fused_recurrent_kda`) + gated MLA + AttnRes + Stable LatentMoE combo has no first-class HF reference to point a tiny-model script at, unlike every oracle this repo has built so far. Building one means either pulling the real upstream repo's custom `trust_remote_code` modeling file (if publicly reachable) or hand-deriving a from-scratch Python reference from `kimi_k3.c`'s own header spec — the latter risks two implementations sharing the same misunderstanding, which defeats the point of an independent oracle.

**Proposed split**, so real progress doesn't wait on that answer:
- **Slice A** (no oracle needed, starting now): reconcile the 17 `set_error` copies to one, and pull every non-attention/non-expert-store unit above into real per-file layout (config, kv_cache, attention_cache, math, resource_plan, head_cache, route_bf16, layer, runtime, prompt) — cuts real duplication and size without touching MLA-shaped code at all.
- **Slice B** (gated by the oracle question): reconcile the 3x `attention_token_impl` — genuinely KDA/MLA-adjacent code, holds per the issue's own precondition.
- **Slice C** (arguably NOT gated — it's an allocator/caching bug, not attention math, and the existing `deepseek-v4-tiny` oracle + `test_deepseek_v4.c` already cover this layer's correctness): reconcile the 3x expert store and fix the live `aligned_slab` Windows mismatch.

Starting Slice A now.

---
_Generated by [Claude Code](https://claude.ai/code)_

**Comment by alpibrupa** [comment]
Correction to my "Slice A" framing above, from actually attempting it.

I collapsed the 14 `set_error` definitions to one and the build broke at **link** time (`undefined reference to set_error` across ~10 object files), not compile time. Reverted immediately (`git checkout`).

The reason reveals the real shape of this problem: **`deepseek_v4.c` is not one logical file — it's 26+ separate translation units stored in one file**, each selected by its own `#ifdef COLI_V4_UNIT_X ... #endif` region and compiled independently:

```
gcc -DCOLI_V4_UNIT_MATH      -c deepseek_v4.c -o COLI_V4_UNIT_MATH.o
gcc -DCOLI_V4_UNIT_ATTENTION -c deepseek_v4.c -o COLI_V4_UNIT_ATTENTION.o
... (26 target units + 5 test-only units, all from Makefile.deepseek-v4.units)
gcc <all 26 .o> -o deepseek_v4
```

`set_error` (and, by the same reasoning, `attention_token_impl`) is duplicated **because it has to be** under this build: each `#ifdef`-guarded region is its own TU, `static` gives it internal linkage, and internal linkage cannot cross TU boundaries at link time. The 14/3 copies aren't copy-paste sloppiness the way `fuzz`-adjacent duplication usually is — they're a direct, structural consequence of "one amalgamated file, N independent compiles." My "safe mechanical slice" assumption was wrong; there is no dedup that's just a text edit here.

**What real de-duplication actually requires** — either:
1. **External linkage + a shared prototype.** Drop `static`, define the shared helper in exactly one unit, declare it `extern` (via `deepseek_v4_internal.h`, which already exists and already centralizes cross-unit types) everywhere else. Only safe if the object providing the real definition is part of *every* final link that needs it — true for the shipped `deepseek_v4` binary (all 26 target units link together already), **not obviously true for the 5 `V4_TEST_UNITS`** (`KV_CACHE`, `ATTENTION_CACHE`, `EXPERT`, `EXPERT_STORE`, `LAYER`, compiled and presumably linked separately per test) — needs tracing each test's actual link recipe before it's safe.
2. **The literal ask**: split each `#ifdef COLI_V4_UNIT_X` region out into a real `deepseek_v4_x.c` file (mechanical text move, matching the marker names already in the file), drop the guards, and change `Makefile.deepseek-v4` to compile each file directly instead of via `-DCOLI_V4_UNIT_X -c deepseek_v4.c`. This is the actual "de-amalgamate... one source of truth per function" bullet, and it's a real build-system change across ~25 new files + the Makefile, not a slice-sized edit.

Both paths are legitimate but substantially bigger than what I scoped this evening — closer in size to #10 or #11's *entire* multi-PR arc than to one slice of it. Given how much has already landed tonight, I'm stopping code changes on #12 here rather than rushing a build-system restructure at the end of a long session. The corrected architecture map above (real multi-TU structure, the internal header, the test-unit linkage question to resolve first) is what the next pass needs to start from.

---
_Generated by [Claude Code](https://claude.ai/code)_
